version: "3.9"
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # helps file watching inside Docker
